spring:
  datasource:
    url: jdbc:h2:mem:books;DATABASE_TO_UPPER=false
    username: bera
    password:
  h2:
    console:
      path: /my-books-console
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none #for letting schema.sql creation
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:sql-data/*.sql
