
INSERT INTO publisher(name) VALUES ('Publisher 01');
INSERT INTO publisher(name) VALUES ('Publisher 02');
INSERT INTO publisher(name) VALUES ('Publisher 03');
INSERT INTO publisher(name) VALUES ('Publisher 04');
INSERT INTO publisher(name) VALUES ('Publisher 05');
INSERT INTO publisher(name) VALUES ('Publisher 06');
INSERT INTO publisher(name) VALUES ('Publisher 07');
INSERT INTO publisher(name) VALUES ('Publisher 08');
INSERT INTO publisher(name) VALUES ('Publisher 09');
INSERT INTO publisher(name) VALUES ('Publisher 10');
INSERT INTO publisher(name) VALUES ('Publisher 11');
INSERT INTO publisher(name) VALUES ('Publisher 12');
INSERT INTO publisher(name) VALUES ('Publisher 13');
INSERT INTO publisher(name) VALUES ('Publisher 14');
INSERT INTO publisher(name) VALUES ('Publisher 15');
INSERT INTO publisher(name) VALUES ('Publisher 16');
INSERT INTO publisher(name) VALUES ('Publisher 17');
INSERT INTO publisher(name) VALUES ('Publisher 18');
INSERT INTO publisher(name) VALUES ('Publisher 19');
INSERT INTO publisher(name) VALUES ('Publisher 20');


INSERT INTO author(first_name, last_name) VALUES ('Adam','Smith');
INSERT INTO author(first_name, last_name) VALUES ('Barbara','Johnson');
INSERT INTO author(first_name, last_name) VALUES ('Charlie','Brown');
INSERT INTO author(first_name, last_name) VALUES ('Diana','Evans');
INSERT INTO author(first_name, last_name) VALUES ('Edward','King');
INSERT INTO author(first_name, last_name) VALUES ('Fiona','Green');
INSERT INTO author(first_name, last_name) VALUES ('George','Miller');
INSERT INTO author(first_name, last_name) VALUES ('Hannah','Davis');
INSERT INTO author(first_name, last_name) VALUES ('Ian','Clark');
INSERT INTO author(first_name, last_name) VALUES ('Jenny','White');
INSERT INTO author(first_name, last_name) VALUES ('Karl','Baker');
INSERT INTO author(first_name, last_name) VALUES ('Linda','Carter');
INSERT INTO author(first_name, last_name) VALUES ('Marvin','Hughes');
INSERT INTO author(first_name, last_name) VALUES ('Nina','Reed');
INSERT INTO author(first_name, last_name) VALUES ('Oscar','Bennett');
INSERT INTO author(first_name, last_name) VALUES ('Paula','Bell');
INSERT INTO author(first_name, last_name) VALUES ('Quincy','Lopez');
INSERT INTO author(first_name, last_name) VALUES ('Rachel','Cooper');
INSERT INTO author(first_name, last_name) VALUES ('Simon','Phillips');
INSERT INTO author(first_name, last_name) VALUES ('Tina','Anderson');


INSERT INTO book(title, price, publisher_id) VALUES ('Book Title 01', 10.99, 1);
INSERT INTO book(title, price, publisher_id) VALUES ('Book Title 02', 20.00, 2);
INSERT INTO book(title, price, publisher_id) VALUES ('Book Title 03', 15.50, 3);
INSERT INTO book(title, price, publisher_id) VALUES ('Book Title 04', 40.20, 4);
INSERT INTO book(title, price, publisher_id) VALUES ('Book Title 05', 12.05, 5);
INSERT INTO book(title, price, publisher_id) VALUES ('Book Title 06', 18.89, 6);
INSERT INTO book(title, price, publisher_id) VALUES ('Book Title 07', 33.33, 7);
INSERT INTO book(title, price, publisher_id) VALUES ('Book Title 08', 44.44, 8);
INSERT INTO book(title, price, publisher_id) VALUES ('Book Title 09', 55.55, 9);
INSERT INTO book(title, price, publisher_id) VALUES ('Book Title 10', 66.66, 10);
INSERT INTO book(title, price, publisher_id) VALUES ('Book Title 11', 27.99, 11);
INSERT INTO book(title, price, publisher_id) VALUES ('Book Title 12', 17.49, 12);
INSERT INTO book(title, price, publisher_id) VALUES ('Book Title 13', 5.99, 13);
INSERT INTO book(title, price, publisher_id) VALUES ('Book Title 14', 100.00, 14);
INSERT INTO book(title, price, publisher_id) VALUES ('Book Title 15', 75.75, 15);
INSERT INTO book(title, price, publisher_id) VALUES ('Book Title 16', 2.50, 16);
INSERT INTO book(title, price, publisher_id) VALUES ('Book Title 17', 11.11, 17);
INSERT INTO book(title, price, publisher_id) VALUES ('Book Title 18', 9.95, 18);
INSERT INTO book(title, price, publisher_id) VALUES ('Book Title 19', 7.77, 19);
INSERT INTO book(title, price, publisher_id) VALUES ('Book Title 20', 22.22, 20);

INSERT INTO book_author(book_id, author_id) VALUES (1, 1);
INSERT INTO book_author(book_id, author_id) VALUES (1, 2);
INSERT INTO book_author(book_id, author_id) VALUES (2, 3);
INSERT INTO book_author(book_id, author_id) VALUES (3, 4);
INSERT INTO book_author(book_id, author_id) VALUES (3, 5);
INSERT INTO book_author(book_id, author_id) VALUES (4, 6);
INSERT INTO book_author(book_id, author_id) VALUES (5, 7);
INSERT INTO book_author(book_id, author_id) VALUES (5, 8);
INSERT INTO book_author(book_id, author_id) VALUES (5, 9);
INSERT INTO book_author(book_id, author_id) VALUES (6, 10);
INSERT INTO book_author(book_id, author_id) VALUES (7, 11);
INSERT INTO book_author(book_id, author_id) VALUES (7, 12);
INSERT INTO book_author(book_id, author_id) VALUES (8, 13);
INSERT INTO book_author(book_id, author_id) VALUES (9, 14);
INSERT INTO book_author(book_id, author_id) VALUES (9, 15);
INSERT INTO book_author(book_id, author_id) VALUES (10, 16);
INSERT INTO book_author(book_id, author_id) VALUES (11, 17);
INSERT INTO book_author(book_id, author_id) VALUES (11, 18);
INSERT INTO book_author(book_id, author_id) VALUES (12, 19);
INSERT INTO book_author(book_id, author_id) VALUES (13, 20);
INSERT INTO book_author(book_id, author_id) VALUES (14, 1);
INSERT INTO book_author(book_id, author_id) VALUES (14, 3);
INSERT INTO book_author(book_id, author_id) VALUES (15, 5);
INSERT INTO book_author(book_id, author_id) VALUES (16, 7);
INSERT INTO book_author(book_id, author_id) VALUES (17, 9);
INSERT INTO book_author(book_id, author_id) VALUES (18, 11);
INSERT INTO book_author(book_id, author_id) VALUES (19, 13);
INSERT INTO book_author(book_id, author_id) VALUES (20, 15);